env:
  node: true
extends:
  - eslint:recommended
  - plugin:n/recommended
parserOptions:
  ecmaVersion: 2022
  sourceType: module
globals:
  ee: readonly
rules:
  n/no-extraneous-import:
    - error
    - allowModules:
      - restify-errors
