name: Run Tests
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 17 # minimum req. version right now
          - lts/*
          - latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
      - run: npm run sync
      - run: npm test
